### ISSUE TITLE
sass-convert: command not found

### ISSUE THREAD

**Issue by martin-braun** [sjova/vscode-sass-format#18]
When I try to format my scss file on my MacBook with cmd+k cmd+d, I get this error: 
`/bin/sh: sass-convert: command not found`

debug info: 
```
marty@MettBook:~$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
marty@MettBook:~$ which ruby
/usr/bin/ruby
marty@MettBook:~$ gem --version
2.5.2
marty@MettBook:~$ which gem
/usr/bin/gem
marty@MettBook:~$ sass-convert
-bash: sass-convert: command not found
marty@MettBook:~$ sass-convert --version
-bash: sass-convert: command not found
marty@MettBook:~$ which sass-convert
marty@MettBook:~$ sass --version
1.1.1 compiled with dart2js 2.0.0-dev.36.0
marty@MettBook:~$ which sass
/Users/marty/node_module_collections/default/bin/sass
marty@MettBook:~$ echo $SHELL
/bin/bash
marty@MettBook:~$ echo $PATH
/Users/marty/node_module_collections/default/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/marty/library/android/sdk/tools:/Users/marty/library/android/sdk/platform-tools:/usr/local/bin/ant:/Users/marty/.composer/vendor/bin
marty@MettBook:~$ echo $GEM_PATH

marty@MettBook:~$ cat ~/.bash_profile
# colorful terminal
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'

# hat env preq
export JAVA_HOME=$(/usr/libexec/java_home)
export ANDROID_HOME="/Users/marty/library/android/sdk"
export ANT_HOME="/usr/local/Cellar/ant/1.9.6/libexec/"
export KAPSEL_HOME="/Users/marty/SAP/MobileSDK3/KapselSDK"
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:/usr/local/bin/ant

# alias to love
alias love="/Applications/love.app/Contents/MacOS/love"
export KAPSEL_HOME=/Users/marty/SAP/MobileSDK3/KapselSDK

# path to composer bins
export PATH=$PATH:$HOME/.composer/vendor/bin

# paths to node_modules from module_collections selection
export PATH=/Users/marty/node_module_collections/default/bin:$PATH

marty@MettBook:~$ cat ~/.bash_login
cat: /Users/marty/.bash_login: No such file or directory
marty@MettBook:~$ cat ~/.profile
cat: /Users/marty/.profile: No such file or directory
```

I tried to install the sass command line tools with `brew install` and with `sudo npm install -g`. In both cases, the `sass` command can be found, though.

**Comment by dylanvdmerwe** [comment]
Same here.

**Comment by sjova** [comment]
Hello @MartyMaro, @dylanvdmerwe, thanks for reporting this issue.

This extension using **Ruby Sass** command line tools from the beggining, which were officially supported until *March 26, 2018*, and **Dart Sass** and JavaScript implementation of Sass is not supported at this moment.

So please use the old official procedure for installing Ruby Sass. More details about transition and old official procedure: https://github.com/sjova/vscode-sass-format#install-ruby-sass-via-command-line

I'll try to replace Ruby Sass with Dart Sass before June 26, 2018 (3 months from official replacement). Please note that pure JavaScript implementation of Sass will not be supported at all because it's slower than Dart Sass and/or Ruby Sass implementation.

**Comment by sjova** [comment]
`sass-convert` functionality is not yet provided in Dart implementation (more details: [GitHub/Dart Sass/Are you planning to implement sass-convert?](https://github.com/sass/dart-sass/issues/188)). I'll close this issue, and you can follow homepage for more updates about this.

I'll wait few more months, or I'll replace `sass-convert` with some alternative (node-sass, Sass.js).
