### ISSUE TITLE
Comments move 2 lines down when formatting

### ISSUE THREAD

**Issue by mvasilkov** [sjova/vscode-sass-format#9]
The SCSS:

```
code,
kbd,
samp {
  font-family: $sys-font-stack-mono; // 1
  font-size: 1em; // 2
}
```

After formatting:

```
code,
kbd,
samp {
    font-family: $sys-font-stack-mono;

    // 1
    font-size: 1em;

    // 2
}
```

Line comments shouldn't do this.

Versions: Windows 10, VS Code 1.17.1, Sass Formatter 1.1.1
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
gem --version: 2.6.13
Sass 3.5.2 (Bleeding Edge)

**Comment by sjova** [comment]
Hello mvasilkov, thanks for reporting this issue.

Sass formatter extension is built on top of `sass-convert`, and reported the issue is the default behavior of sass-convert tool. If you try to use sass-convert as a standalone console tool you will get same results.

In latest `1.1.2` version I introduced new setting `sassFormat.inlineComments` as experimental support to preserve inline comments inline. I was modified string content before and after sass-convert formatting to accomplish this if above setting is `true`.

Please update the extension to the latest version, and let me know if everything works fine now.

Thanks

**Comment by mvasilkov** [comment]
Fantastic! Thanks a lot 🥇
